server {

    listen 80;
    server_name localhost;
    #root /usr/share/nginx/html;
    #index index.html;

    location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                #proxy_pass http://aue1ecsd02-node1.ricohonline.org:5373;  #Dev
                #proxy_pass http://aue1ecsq01-node1.ricohonline.org:6373;   #QA
                #proxy_pass http://aue1ecsu01-node1.ricohonline.org:7373;  #Uat
                proxy_pass http://aue1ecsp02-node1.ricohonline.org:7373;  #Prod
        }

    location /static/ {
            include /etc/nginx/mime.types;
            alias /static/;
            try_files $uri $uri/ /;
    }

        location /assets/img/ {
            include /etc/nginx/mime.types;
            alias /assets/img/;
        }


    #    location /assets/icons/ {
    #        include /etc/nginx/mime.types;
    #        alias /assets/icons/;
    #    }

        # location /{
        #         try_files $uri $uri/ ceft_app/index.html?/$request_uri;                
        #   }
          
}
