DELIMITER //
CREATE PROCEDURE `RAC_FS_TM_EMP_CHANGE_SUBMIT_PROCEDURE`(IN P_IN_CHANGE_ID BIGINT(10))
BEGIN

DECLARE v_change_id                	INTEGER DEFAULT 0;
DECLARE v_CHANGE_EFFECTIVE_DATE     TIMESTAMP;
DECLARE v_EMPLOYEE_ID               BIGINT (10);
DECLARE v_JOB_TYPE                  VARCHAR (150);
DECLARE v_JOB_TITLE                 VARCHAR (150);
DECLARE v_JOB_FAMILY                VARCHAR (150);
DECLARE v_JOB_ADP                   VARCHAR (150);
DECLARE v_TEAM_TYPE                 VARCHAR (150);
DECLARE v_MANAGER_ID                BIGINT (10);
DECLARE v_MANAGER_FLAG              VARCHAR (30);
DECLARE v_ADMIN_NOTES               VARCHAR (2000); 
DECLARE v_SERVICE_START_DATE        TIMESTAMP;
DECLARE v_SERVICE_END_DATE          TIMESTAMP;
DECLARE v_WORK_SHIFT                VARCHAR (30);
DECLARE v_ON_CALL                   VARCHAR (30);
DECLARE v_ON_SITE                   VARCHAR (30);
DECLARE v_SERVICE_ADVANTAGE         VARCHAR (150);
DECLARE v_PRODUCTION_TYPE           VARCHAR (150);
DECLARE v_RECORD_COMPLETE           VARCHAR (150);
DECLARE v_DEDICATED                 VARCHAR (30);
DECLARE v_DEDICATED_TO              VARCHAR (150);
DECLARE v_LOC_CODE                  VARCHAR (150);
DECLARE v_AREA                      VARCHAR (150);
DECLARE v_REGION                    VARCHAR (150);
DECLARE v_PRODUCTION_PRINT          VARCHAR (10);
DECLARE v_OFSC_STATUS               VARCHAR (100);
DECLARE v_ALTERNATE_EMAIL           VARCHAR (400);
DECLARE v_REVIEW_DATE               TIMESTAMP;
DECLARE v_CHANGE_NOTE               VARCHAR(2000);
DECLARE v_CHANGE_TYPE               VARCHAR (30);
DECLARE v_CHANGE_STATUS             VARCHAR (30);
DECLARE v_FS_STATUS                 VARCHAR (30);
DECLARE v_HR_STATUS                 VARCHAR (30);
DECLARE v_REQUESTED_BY              VARCHAR (30);
DECLARE v_APPROVAL_REQUIRED         VARCHAR (30);
DECLARE v_CSA_NOTIFICATION_REQUIRED VARCHAR (30);
DECLARE v_job_id                    BIGINT (10);
DECLARE v_area_id                   BIGINT (10);
DECLARE v_team_type_id              BIGINT (10);


	CALL RAC_FS_TM_WRITE_LOG_MESSAGES('RAC_FS_TM_EMP_CHANGE_SUBMIT_PROCEDURE','Begin Procedure');
	
	/****Calling procedure to set approval flag****/
	CALL RAC_FS_TM_APPROVAL_FLAG_PROCEDURE(P_IN_CHANGE_ID);
	
	/****Calling procedure to set csa flag****/
	CALL RAC_FS_TM_CSA_FLAG_PROCEDURE(P_IN_CHANGE_ID);
	
		SELECT CHANGE_EFFECTIVE_DATE,
	       EMPLOYEE_ID,
		   JOB_TYPE,
		   JOB_TITLE,
		   JOB_ADP,
		   TEAM_TYPE,
		   MANAGER_ID,
		   MANAGER_FLAG,
		   ADMIN_NOTES,
		   SERVICE_START_DATE,
		   SERVICE_END_DATE,
		   WORK_SHIFT,
		   ON_CALL,
		   ON_SITE,
		   SERVICE_ADVANTAGE,
		   PRODUCTION_TYPE,
		   RECORD_COMPLETE,
		   DEDICATED,
		   DEDICATED_TO,
		   LOC_CODE,
		   AREA,
		   REGION,
		   REVIEW_DATE,
		   CHANGE_NOTE,
		   CHANGE_TYPE,
		   CHANGE_STATUS,
		   FS_STATUS,
		   REQUESTED_BY,
		   APPROVAL_REQUIRED,
		   CSA_NOTIFICATION_REQUIRED
	  INTO v_CHANGE_EFFECTIVE_DATE,
	       v_EMPLOYEE_ID,
		   v_JOB_TYPE,
		   v_JOB_TITLE,
		   v_JOB_ADP,
		   v_TEAM_TYPE,
		   v_MANAGER_ID,
		   v_MANAGER_FLAG,
		   v_ADMIN_NOTES,
		   v_SERVICE_START_DATE,
		   v_SERVICE_END_DATE,
		   v_WORK_SHIFT,
		   v_ON_CALL,
		   v_ON_SITE,
		   v_SERVICE_ADVANTAGE,
		   v_PRODUCTION_TYPE,
		   v_RECORD_COMPLETE,
		   v_DEDICATED,
		   v_DEDICATED_TO,
		   v_LOC_CODE,
		   v_AREA,
		   v_REGION,
		   v_REVIEW_DATE,
		   v_CHANGE_NOTE,
		   v_CHANGE_TYPE,
		   v_CHANGE_STATUS,
		   v_FS_STATUS,
		   v_REQUESTED_BY,
		   v_APPROVAL_REQUIRED,
		   v_CSA_NOTIFICATION_REQUIRED
	FROM RAC_FS_TM_EMPLOYEE_UPD
	WHERE CHANGE_ID = P_IN_CHANGE_ID
	  AND CHANGE_STATUS = 'Pending';

    IF v_APPROVAL_REQUIRED = 'N' AND v_CHANGE_EFFECTIVE_DATE <= CURRENT_TIMESTAMP
	THEN
	  /*
	    IF v_JOB_ADP IS NOT NULL 
		THEN
		 SELECT JOB_ID 
		   INTO v_job_id
		   FROM RAC_FS_TM_JOB_CODE 
		  WHERE JOB_ADP =v_JOB_ADP
		     AND upper(STATUS)='ACTIVE';
		
		END IF;
		
		IF v_TEAM_TYPE IS NOT NULL
		THEN
		 SELECT TEAM_TYPE_ID 
		   INTO v_team_type_id
		   FROM RAC_FS_TM_TEAM_TYPE 
		  WHERE TEAM_TYPE = v_TEAM_TYPE
		  AND upper(STATUS)='ACTIVE';
		
		END IF;
		
		IF v_REGION is not null and v_AREA IS NOT NULL
		THEN
		 SELECT area_id 
		   INTO v_area_id
		   FROM RAC_FS_REGION region,RAC_FS_AREA area
		  WHERE region.REGION = v_REGION
		  AND region.area_id= area.area_id
		  AND area.Area_short = v_AREA
		  AND upper(STATUS)='ACTIVE';
		
		END IF;
		
		*/
		/*Update  RAC_FS_TM_EMPLOYEE_DTLS
		Set JOB_ID=  IF (v_job_id IS NULL,JOB_ID,v_job_id),
		    TEAM_TYPE_ID = IF (v_TEAM_TYPE_id IS NULL,TEAM_TYPE_ID,v_TEAM_TYPE_id),
		    MANAGER_EMPLOYEE_ID = IF (v_manager_id IS NULL,MANAGER_EMPLOYEE_ID,v_manager_id),
		    MANAGER_FLAG = IF (v_MANAGER_FLAG IS NULL,MANAGER_FLAG,v_MANAGER_FLAG),
			SERVICE_START_DATE = IF (v_SERVICE_START_DATE IS NULL,SERVICE_START_DATE,v_SERVICE_START_DATE),
			SERVICE_END_DATE = IF (v_SERVICE_END_DATE IS NULL,SERVICE_END_DATE,v_SERVICE_END_DATE),
			WORK_SHIFT = IF (v_WORK_SHIFT IS NULL,WORK_SHIFT,v_WORK_SHIFT),
			ON_CALL = IF (v_ON_CALL IS NULL,ON_CALL,v_ON_CALL),
			ON_SITE = IF (v_ON_SITE IS NULL,ON_SITE,v_ON_SITE),
			SERVICE_ADVANTAGE = IF (v_SERVICE_ADVANTAGE IS NULL,SERVICE_ADVANTAGE,v_SERVICE_ADVANTAGE),
			RECORD_COMPLETE = IF (v_RECORD_COMPLETE IS NULL,RECORD_COMPLETE,v_RECORD_COMPLETE),
			DEDICATED = IF (v_DEDICATED IS NULL,DEDICATED,v_DEDICATED),
			DEDICATED_TO = IF (v_DEDICATED_TO IS NULL,DEDICATED_TO,v_DEDICATED_TO),
			LOC_CODE = IF (v_LOC_CODE IS NULL,LOC_CODE,v_LOC_CODE),
			AREA_ID = IF (v_AREA IS NULL,AREA_ID,v_area),
			FS_STATUS = IF (v_MANAGER_FLAG IS NULL,FS_STATUS,v_MANAGER_FLAG)
		Where employee_id=v_EMPLOYEE_ID;
		*/
		UPDATE RAC_FS_TM_EMPLOYEE_UPD
		SET CHANGE_STATUS = 'Approved',
            approved = 'Y',
            approved_by = v_REQUESTED_BY,
		    processed_date = CURRENT_DATE,
			last_update_date = CURRENT_TIMESTAMP,
			last_updated_by = v_REQUESTED_BY
		WHERE change_id=P_IN_CHANGE_ID;
		
		COMMIT;
	END IF;	
END
//
DELIMITER ;
