CREATE TABLE `RAC_FS_TM_LOC` (
  `LOC_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOCATION_CODE` varchar(400) DEFAULT NULL,
  `DESCRIPTION` varchar(400) DEFAULT NULL,
  `ZIP_CODE` varchar(30) DEFAULT NULL,
  `INACTIVE_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(400) DEFAULT 'AWS',
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(400) DEFAULT 'AWS',
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`LOC_ID`)
) ;
