CREATE TABLE `RAC_FS_TM_USER_DETAILS` (
  `EMPLOYEE_ID` bigint(10) NOT NULL,
  `EMPLOYEE_NAME` varchar(1000) DEFAULT NULL,
  `EMAIL` varchar(1000) DEFAULT NULL,
  `ROLE` varchar(150) DEFAULT NULL,
  `LAST_LOGIN` datetime DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`)
) ;
