CREATE TABLE `RAC_FS_TM_TEAM_TYPE` (
  `TEAM_TYPE_ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `TEAM_TYPE_NAME` varchar(150) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  `EFFECTIVE_START_DATE` timestamp NULL DEFAULT NULL,
  `EFFECTIVE_END_DATE` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(400) DEFAULT 'AWS',
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(400) DEFAULT 'AWS',
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`TEAM_TYPE_ID`),
  UNIQUE KEY `TEAM_TYPE_NAME` (`TEAM_TYPE_NAME`)
) ;
