CREATE TABLE `RAC_FS_TM_NOTIF` (
  `NOTIFICATION_ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_NAME` varchar(150) NOT NULL,
  `EMAIL_ID` varchar(300) DEFAULT NULL,
  `NOTIFICATION_SUBJECT` varchar(1000) DEFAULT NULL,
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(150) DEFAULT 'AWS',
  `STATUS` varchar(30) DEFAULT NULL,
  `EFFECTIVE_START_DATE` timestamp NULL DEFAULT NULL,
  `EFFECTIVE_END_DATE` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(150) DEFAULT 'AWS',
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`NOTIFICATION_ID`)
);
