CREATE TABLE `RAC_FS_TM_SYNC_LOGS` (
  `TM_LOG_ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` bigint(10) DEFAULT NULL,
  `RESOURCE_NUMBER` varchar(100) DEFAULT NULL,
  `INSTANCE_ID` bigint(10) DEFAULT NULL,
  `LOGIN` varchar(300) DEFAULT NULL,
  `ERR_MSG` varchar(5000) DEFAULT NULL,
  `SYNC_PROCESS` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(400) DEFAULT 'AWS',
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(400) DEFAULT 'AWS',
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`TM_LOG_ID`)
);
