CREATE TABLE `RAC_FS_TM_LOGS` (
  `TM_LOG_ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `EMAIL_ID` varchar(300) DEFAULT NULL,
  `LAMBDA_STATUS` varchar(100) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `PROCEDURE_NAME` varchar(250) DEFAULT NULL,
  `MSG` varchar(5000) DEFAULT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(400) DEFAULT 'AWS',
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(400) DEFAULT 'AWS',
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`TM_LOG_ID`)
) ;
