CREATE TABLE `RAC_FS_TM_REQ_CLMS` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT,
  `FIELD_NAME` varchar(100) DEFAULT NULL,
  `APPROVAL_REQ` varchar(10) DEFAULT NULL,
  `CSA_NOTIFICATION_FLAG` varchar(10) DEFAULT NULL,
  `CREATION_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(150) DEFAULT 'AWS',
  `LAST_UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(150) DEFAULT 'AWS',
  `ATTRIBUTE1` varchar(400) DEFAULT NULL,
  `ATTRIBUTE2` varchar(400) DEFAULT NULL,
  `ATTRIBUTE3` varchar(400) DEFAULT NULL,
  `ATTRIBUTE4` varchar(400) DEFAULT NULL,
  `ATTRIBUTE5` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;
