from app.components.configuration.area.main import area_router
from app.components.configuration.job_code.main import job_code_router
from app.components.configuration.location.main import location_router
from app.components.configuration.region.main import region_router
from app.components.configuration.team_type.main import team_type_router
from app.components.home.main import home_router
from app.components.configuration.common.main import common_router
from app.components.employee.main import employee_router
from app.components.view.main import view_router
from app.components.changes.main import changes_router
from app.components.configuration.notification_set_up.main import notification_router
from app.components.log.main import log_router
from app.components.reports.main import report_router
